name: epi2melabs-nf-artic
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - aplanat =0.5.4
    - fastcat =0.3.6
    - bioconda::nextclade =1.5.1
    - np-artic =1.3.0=py_9
    - pomoxis =0.3.6
